In [71]:

# Pandas and numpy for data wrangling
import pandas as pd
import numpy as np

# Helper function to split our data
from sklearn.model_selection import train_test_split

#min max scale
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()

# This is our perceptron model
from sklearn.linear_model import Perceptron

# Helper fuctions to evaluate our model.
from sklearn.metrics import accuracy_score

In [72]:
df = pd.read_csv('data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [73]:
#useless columns
df = df.drop(columns = ['id','Unnamed: 32'])


In [74]:
#changing values of diagnosis
df['diagnosis'] = df.diagnosis.apply(lambda x: 1 if x =='M' else -1)


In [75]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38          122.80     1001.0   
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
3          1        11.42         20.38           77.58      386.1   
4          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Preparing training set

In [76]:
#X and y features
X = df.drop(columns = 'diagnosis')
X = minmax.fit_transform(X)
X = np.c_[np.ones(X.shape[0]),X]
y = df['diagnosis'].to_numpy()
X,y


(array([[1.        , 0.52103744, 0.0226581 , ..., 0.91202749, 0.59846245,
         0.41886396],
        [1.        , 0.64314449, 0.27257355, ..., 0.63917526, 0.23358959,
         0.22287813],
        [1.        , 0.60149557, 0.3902604 , ..., 0.83505155, 0.40370589,
         0.21343303],
        ...,
        [1.        , 0.45525108, 0.62123774, ..., 0.48728522, 0.12872068,
         0.1519087 ],
        [1.        , 0.64456434, 0.66351031, ..., 0.91065292, 0.49714173,
         0.45231536],
        [1.        , 0.03686876, 0.50152181, ..., 0.        , 0.25744136,
         0.10068215]]),
 array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1, -1, -1,
        -1, -1,  1,  1, -1,  1,  1, -1, -1, -1, -1,  1, -1,  1,  1, -1, -1,
        -1, -1,  1, -1,  1,  1, -1,  1, -1,  1,  1, -1, -1, -1,  1,  1, -1,
         1,  1,  1, -1, -1, -

In [77]:
w = np.random.randn(31)
w


array([ 1.7843601 ,  0.13851841, -1.66719474, -1.72803725,  2.1284026 ,
        0.25951265, -0.11857037, -1.07942763,  1.72696498,  0.32696946,
        1.49840727, -1.25297774, -0.2248568 ,  0.31092668,  1.00972057,
        0.64729919,  0.62631718,  0.18906269, -0.55417733, -1.03072699,
        0.29872266, -1.5506914 , -0.89013021,  0.49812516, -0.25236888,
        0.90974933,  0.6727764 , -0.48658001, -0.33770371, -0.12842472,
        0.09246074])

In [78]:
phi = lambda z: (z >= 0)*2 -1

# Perceptron
### 100 epochs

In [79]:
eta = 0.1
for i in range(100):
    for x,y_i in zip(X,y):
        yhat = phi(w.T@x)
        dw_0 = eta*(y_i-yhat)*x
        w += dw_0
   

In [80]:
w

array([-3.6156399 , -0.35576906,  0.84751612, -2.18275358,  2.30163696,
       -0.04927131, -1.06684348,  0.87134885,  2.3002294 , -0.7826265 ,
       -0.59460032,  2.59526416, -0.84703679,  2.47333539,  3.17039879,
        0.61055173, -1.57325021, -0.25083479,  0.44791397, -0.15819082,
       -1.22786137,  0.82501832,  1.34734313,  2.0036085 ,  2.04553222,
        1.11622097,  0.23772871,  1.01596791, -0.15301642,  1.58996676,
        0.98222854])

In [81]:
y_pred = phi(X@w)
y_pred

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,
        1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1, -1, -1, -1,  1,  1,  1,  1, -1,  1, -1, -1, -1,
       -1, -1,  1,  1, -1,  1,  1, -1, -1, -1, -1,  1, -1,  1,  1, -1, -1,
       -1, -1,  1, -1,  1, -1, -1,  1, -1,  1,  1, -1, -1, -1,  1,  1, -1,
        1, -1,  1, -1, -1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1,  1, -1,
       -1, -1, -1,  1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,
        1, -1,  1,  1, -1, -1, -1,  1,  1, -1,  1, -1,  1,  1, -1,  1, -1,
       -1, -1,  1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1,  1, -1, -1, -1, -1,  1,  1, -1,  1, -1, -1,  1,  1, -1,
       -1,  1,  1, -1, -1, -1, -1,  1, -1, -1,  1,  1,  1, -1, -1, -1,  1,
       -1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1,  1,  1, -1,  1,  1,  1,
       -1, -1, -1,  1, -1, -1,  1, -1,  1, -1,  1, -1, -1, -1,  1,  1, -1,
       -1, -1,  1, -1, -1

# Training accuracy

In [82]:
accuracy = accuracy_score(y,yhat)
accuracy

0.9543057996485061